# .github/workflows/deploy_web.yml

name: Build & Deploy Flutter Web to docs/

on:
  push:
    branches:
      - main
  workflow_dispatch:    # 允许在 Actions 页面手动触发

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'
      - name: Install dependencies
        run: |
          cd avalon
          flutter pub get
      - name: Build Web Release
        run: |
          cd avalon
          flutter build web --release
      - name: Deploy to docs/
        run: |
          rm -rf docs
          mv avalon/build/web docs
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"
          git add docs
          git commit -m "chore: deploy Flutter web to docs/" || echo "No changes to commit"
          git push origin main
