# .github/workflows/deploy_web.yml

name: Deploy Flutter Web to GitHub Pages (/docs)

on:
  push:
    branches:
      - main
  workflow_dispatch:

  jobs:
    build-and-deploy:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
          with:
            persist-credentials: true
            fetch-depth: 0

        - name: Setup Flutter
          uses: subosito/flutter-action@v2
          with:
            channel: stable

        - name: Install dependencies
          run: |
            cd avalon
            flutter pub get

        - name: Build Web Release
          run: |
            cd avalon
            flutter build web --release

        - name: Prepare docs directory
          run: |
            rm -rf docs
            cp -r avalon/build/web docs

        - name: Fix base href for GitHub Pages
          run: |
            sed -i 's|<base href="/">|<base href="./">|' docs/index.html

        - name: Commit and Push docs
          run: |
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git add docs
            git diff --quiet || git commit -m "chore: deploy web to docs [skip ci]"
            git push origin main
