# .github/workflows/deploy_web.yml

name: Deploy Flutter Web to GitHub Pages (/docs)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repository
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. Install Flutter (stable channel)
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. Install dependencies
      - name: Install dependencies
        run: |
          cd avalon
          flutter pub get

      # 4. Build the web release
      - name: Build Web Release
        run: |
          cd avalon
          flutter build web --release

      # 5. Copy build output into docs/
      - name: Prepare docs directory
        run: |
          rm -rf docs
          cp -r avalon/build/web docs

      # 6. Fix <base> for GitHub Pages subdirectory
      - name: Fix base href for GitHub Pages
        run: |
          # Ensure resources load under /Avalon/ or your repo name
          sed -i 's|<base href="/">|<base href="./">|' docs/index.html

      # 7. Commit and push docs/
      - name: Commit and Push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          # Only commit if there are changes
          git diff --quiet || git commit -m "chore: deploy web to docs [skip ci]"
          git push origin main
