# .github/workflows/deploy_web.yml

name: Deploy Flutter Web to GitHub Pages (/docs)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. 签出代码并保留凭据，方便后续 git push
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true
          fetch-depth: 0

      # 2. 安装 Flutter SDK（使用 channel 而非 flutter-version）
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      # 3. 安装依赖
      - name: Install dependencies
        run: |
          cd avalon
          flutter pub get

      # 4. 构建 Web release
      - name: Build Web Release
        run: |
          cd avalon
          flutter build web --release

      # 5. 准备 docs 目录
      - name: Prepare docs directory
        run: |
          rm -rf docs
          cp -r avalon/build/web docs

      # 6. 提交并推送到 main（更新 docs/）
      - name: Commit and Push docs
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git diff --quiet || git commit -m "chore: deploy web to docs [skip ci]"
          git push origin main
